[package]
name = "erenjr/24-game-roblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.7.0"
Component = "sleitnick/component@2.4.8"
Silo = "sleitnick/silo@0.2.0"

[server-dependencies]
Component = "daimondnetwork/component@^2.0.0"

[dev-dependencies]
