local GamePasses = {
	{
		GamePassId = 1696596147,
		Name = "Double Coins",
		Description = "Earn 2x coins from kills and rewards",
		PriceRobux = 499,
		PriceCoins = 2000,
		Icon = "💫",
	},
	{
		GamePassId = 1696759076,
		Name = "Extra Health",
		Description = "Start with 200 max health instead of 100",
		PriceRobux = 299,
		PriceCoins = 1500,
		Icon = "❤️‍🔥",
	},
	{
		GamePassId = 1696640103,
		Name = "Extra Health*10",
		Description = "Start with 2000 max health instead of 100",
		PriceRobux = 2990,
		PriceCoins = 15000,
		Icon = "❤️‍🔥",
	},
}

return GamePasses
