local Questions = {
	{ numbers = {24} },
	{ numbers = {12, 12} },
	{ numbers = {8, 8, 8} },
	{ numbers = {6, 6, 6, 6} },
	{ numbers = {10, 8, 6} },
	{ numbers = {7, 7, 7, 3} },
	{ numbers = {4, 4, 4, 12} },
	{ numbers = {3, 3, 3, 15} },
	{ numbers = {2, 4, 6, 12} },
	{ numbers = {5, 5, 5, 9} },
	{ numbers = {1, 2, 3, 18} },
	{ numbers = {7, 8, 9} },
	{ numbers = {11, 13} },
	{ numbers = {1, 1, 1, 21} },
	{ numbers = {14, 10} },
}

return Questions
