name: Rojo Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1

      - name: Install Wally packages
        run: wally install

      - name: Build with Rojo
        run: rojo build default.project.json --output out/24-game.rbxl
